<?php

/**
 * @file
 * Contains ux_form.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_preprocess_select().
 */
function ux_form_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'ux_form/ux_form';
  $form['#attributes']['class'][] = 'ux-form';
}

/**
 * Implements hook_element_info_alter().
 */
function ux_form_element_info_alter(&$type) {
  $input_elements = ['textfield', 'textarea', 'number', 'tel', 'url', 'email', 'password', 'date'];
  foreach ($input_elements as $input_element) {
    if (isset($type[$input_element])) {
      $type[$input_element]['#process'][] = 'ux_form_input_process';
    }
  }

  $input_elements = ['radio', 'radios'];
  foreach ($input_elements as $input_element) {
    if (isset($type[$input_element])) {
      $type[$input_element]['#process'][] = 'ux_form_radio_process';
    }
  }

  $input_elements = ['checkbox', 'checkboxes'];
  foreach ($input_elements as $input_element) {
    if (isset($type[$input_element])) {
      $type[$input_element]['#process'][] = 'ux_form_checkbox_process';
    }
  }

  if (isset($type['text_format'])) {
    $type['text_format']['#process'][] = 'ux_form_text_format_process';
  }

  if (isset($type['select'])) {
    $type['select']['#process'][] = 'ux_form_select_process';
  }

  if (isset($type['date'])) {
    $type['date']['#process'][] = 'ux_form_date_process';
  }

  if (isset($type['datetime'])) {
    $type['datetime']['#process'][] = 'ux_form_datetime_process';
  }
}

/**
 * Process radio elements.
 */
function ux_form_input_process(&$element, FormStateInterface $form_state, &$complete_form) {
  $type = $element['#type'];
  $element['#wrapper_attributes']['class'][] = 'ux-form-input';
  $element['#attached']['library'][] = 'ux_form/ux_form.input';
  if ($type == 'textarea' && !empty($element['#format'])) {
    $element['#wrapper_attributes']['class'][] = 'ux-form-format';
    $element['#wrapper_attributes']['class'][] = 'force-active';
  }
  return $element;
}

/**
 * Process radio elements.
 */
function ux_form_radio_process(&$element, FormStateInterface $form_state, &$complete_form) {
  $type = $element['#type'];
  $element['#wrapper_attributes']['class'][] = 'ux-form-radio';
  $element['#attached']['library'][] = 'ux_form/ux_form.radio';
  if ($type == 'radios') {
    $element['#attributes']['class'][] = 'ux-form-radios';
  }
  return $element;
}

/**
 * Process checkbox elements.
 */
function ux_form_checkbox_process(&$element, FormStateInterface $form_state, &$complete_form) {
  $type = $element['#type'];
  $element['#wrapper_attributes']['class'][] = 'ux-form-checkbox';
  $element['#attached']['library'][] = 'ux_form/ux_form.checkbox';
  if ($type == 'checkboxes') {
    $element['#attributes']['class'][] = 'ux-form-checkboxes';
  }
  return $element;
}

/**
 * Process text format elements.
 */
function ux_form_text_format_process(&$element, FormStateInterface $form_state, &$complete_form) {
  // $element['#attached']['library'][] = 'ux_form/ux_form.select';
  // $element['#attributes']['class'][] = 'POOP';
  return $element;
}

/**
 * Process select elements.
 */
function ux_form_select_process(&$element, FormStateInterface $form_state, &$complete_form) {
  $element['#wrapper_attributes']['class'][] = 'ux-form-select';
  $element['#attached']['library'][] = 'ux_form/ux_form.select';
  if (isset($element['#multiple']) && $element['#multiple']) {
    $element['#attached']['library'][] = 'ux_form/ux_form.checkbox';
  }
  return $element;
}

/**
 * Process date elements.
 */
function ux_form_date_process(&$element, FormStateInterface $form_state, &$complete_form) {
  $element['#wrapper_attributes']['class'][] = 'ux-form-date';
  if (!empty($element['#attached']['library'])) {
    $element['#attached']['library'] = array_filter($element['#attached']['library'], function ($library) {
      return $library !== 'core/drupal.date';
    });
    $element['#attached']['library'][] = 'ux_form/ux_form.date';
  }
  return $element;
}

/**
 * Process datetime elements.
 */
function ux_form_datetime_process(&$element, FormStateInterface $form_state, &$complete_form) {
  $element['#wrapper_attributes']['class'][] = 'ux-form-time';
  $element['#theme_wrappers'] = ['form_element'];
  $element['#attributes']['class'][] = 'ux-form-inline';
  $element['#attached']['library'][] = 'ux_form/ux_form.time';
  $element['date']['#attributes']['placeholder'] = t('Date');
  $element['time']['#attributes']['placeholder'] = t('Time');
  return $element;
}
