<?php

/**
 * @file
 * Contains ux_form.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Component\Utility\Html;

/**
 * Provides theme registration for themes across .inc files.
 */
function ux_form_theme() {
  return [
    'ux_form_element_container' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_preprocess_select().
 */
function ux_form_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (ux_form_access()) {
    $form['#attached']['library'][] = 'ux_form/ux_form';
    $form['#attributes']['class'][] = 'ux-form';
  }
}

/**
 * Implements hook_library_info_alter().
 */
function ux_form_library_info_alter(&$libraries, $extension) {
  if ($extension == 'webform' && isset($libraries['webform.element.inputmask'])) {
    $libraries['webform.element.inputmask']['js']['/' . drupal_get_path('module', 'ux_form') . '/js/modules/webform/webform.element.inputmask.js'] = $libraries['webform.element.inputmask']['js']['js/webform.element.inputmask.js'];
    unset($libraries['webform.element.inputmask']['js']['js/webform.element.inputmask.js']);
  }
}

/**
 * Check if ux_form should be used.
 *
 * @return bool
 *   Returns TRUE if ux_form should be used.
 */
function ux_form_access() {
  $status = &drupal_static(__FUNCTION__);
  if (!isset($status)) {
    $status = FALSE;
    $active_theme = \Drupal::theme()->getActiveTheme()->getName();
    $themes = \Drupal::config('ux_form.settings')->get('themes');
    if (isset($themes[$active_theme])) {
      $status = TRUE;
    }
  }
  return $status;
}

/**
 * Implements hook_element_info_alter().
 */
function ux_form_element_info_alter(&$type) {
  $input_elements = ['textfield', 'textarea', 'number', 'tel', 'url', 'email', 'password', 'date', 'search'];
  foreach ($input_elements as $input_element) {
    if (isset($type[$input_element])) {
      $type[$input_element]['#process'][] = 'ux_form_input_process';
    }
  }

  $input_elements = ['radio', 'radios', 'webform_entity_radios'];
  foreach ($input_elements as $input_element) {
    if (isset($type[$input_element])) {
      $type[$input_element]['#process'][] = 'ux_form_radio_process';
    }
  }

  $input_elements = ['checkbox', 'checkboxes', 'webform_entity_checkboxes'];
  foreach ($input_elements as $input_element) {
    if (isset($type[$input_element])) {
      $type[$input_element]['#process'][] = 'ux_form_checkbox_process';
    }
  }

  $input_elements = ['select', 'webform_entity_select'];
  foreach ($input_elements as $input_element) {
    if (isset($type[$input_element])) {
      $type[$input_element]['#process'][] = 'ux_form_select_process';
    }
  }

  if (isset($type['text_format'])) {
    $type['text_format']['#process'][] = 'ux_form_text_format_process';
  }

  if (isset($type['date'])) {
    $type['date']['#process'][] = 'ux_form_date_process';
  }

  if (isset($type['datetime'])) {
    $type['datetime']['#process'][] = 'ux_form_datetime_process';
  }

  if (isset($type['managed_file'])) {
    $type['managed_file']['#process'][] = 'ux_form_managed_file_process';
  }
}

/**
 * Process input elements.
 */
function ux_form_input_process(&$element, FormStateInterface $form_state, &$complete_form) {
  if (ux_form_access()) {
    $type = $element['#type'];
    $element['#theme_wrappers'][] = 'ux_form_element_container';
    $element['#wrapper_attributes']['class'][] = 'ux-form-input';
    $element['#wrapper_attributes']['class'][] = 'ux-form-input-js';
    $element['#attributes']['class'][] = 'ux-form-input-item';
    $element['#attributes']['class'][] = 'ux-form-input-item-js';
    $element['#attached']['library'][] = 'ux_form/ux_form.input';
    if ($type == 'textarea' && (!empty($element['#allowed_formats']) || !empty($element['#format']))) {
      $element['#wrapper_attributes']['class'][] = 'ux-form-format';
      $element['#wrapper_attributes']['class'][] = 'force-active';
    }
  }
  return $element;
}

/**
 * Process radio elements.
 */
function ux_form_radio_process(&$element, FormStateInterface $form_state, &$complete_form) {
  if (ux_form_access()) {
    $type = $element['#type'];
    $element['#wrapper_attributes']['class'][] = 'ux-form-radio';
    $element['#attached']['library'][] = 'ux_form/ux_form.radio';
    if ($type == 'radio') {
      if (!empty($element['#title'])) {
        $element['#title'] = '<div class="ux-ripple"></div>' . $element['#title'];
      }
    }
    else {
      // $element['#theme_wrappers'][] = 'ux_form_element_container';
      $element['#attributes']['class'][] = 'ux-form-element';
      $element['#attributes']['class'][] = 'ux-form-radios';
    }
  }
  return $element;
}

/**
 * Process checkbox elements.
 */
function ux_form_checkbox_process(&$element, FormStateInterface $form_state, &$complete_form) {
  if (ux_form_access()) {
    $type = $element['#type'];
    if ($type == 'checkbox') {
      $element['#wrapper_attributes']['class'][] = 'ux-form-checkbox';
      $element['#attached']['library'][] = 'ux_form/ux_form.checkbox';
      if (!empty($element['#title'])) {
        $element['#title'] = '<div class="ux-ripple"></div>' . $element['#title'];
      }
    }
    else {
      // $element['#theme_wrappers'][] = 'ux_form_element_container';
      $element['#attributes']['class'][] = 'ux-form-element';
      $element['#attributes']['class'][] = 'ux-form-checkboxes';
    }
  }
  return $element;
}

/**
 * Process select elements.
 */
function ux_form_select_process(&$element, FormStateInterface $form_state, &$complete_form) {
  if (ux_form_access()) {
    // Make sure this is not a UX | Select as links.
    if (!isset($element['#theme']) || $element['#theme'] != 'ux_select_as_links') {
      $element['#theme_wrappers'][] = 'ux_form_element_container';
      $element['#wrapper_attributes']['class'][] = 'ux-form-select';
      $element['#attached']['library'][] = 'ux_form/ux_form.select';
      if (isset($element['#multiple']) && $element['#multiple']) {
        $element['#attached']['library'][] = 'ux_form/ux_form.checkbox';
      }
    }
  }
  return $element;
}

/**
 * Process date elements.
 */
function ux_form_date_process(&$element, FormStateInterface $form_state, &$complete_form) {
  if (ux_form_access()) {
    $element['#theme_wrappers'][] = 'ux_form_element_container';
    $element['#wrapper_attributes']['class'][] = 'ux-form-date';
    if (!empty($element['#attached']['library'])) {
      $element['#attached']['library'] = array_filter($element['#attached']['library'], function ($library) {
        return $library !== 'core/drupal.date';
      });
      $element['#attached']['library'][] = 'ux_form/ux_form.date';
    }
  }
  return $element;
}

/**
 * Process datetime elements.
 */
function ux_form_datetime_process(&$element, FormStateInterface $form_state, &$complete_form) {
  if (ux_form_access()) {
    $element['#wrapper_attributes']['class'][] = 'ux-form-time';
    $element['#theme_wrappers'] = ['form_element'];
    $element['#theme_wrappers'][] = 'ux_form_element_container';
    $element['#attributes']['class'][] = 'ux-form-inline';
    $element['#attached']['library'][] = 'ux_form/ux_form.time';
    $element['date']['#attributes']['placeholder'] = t('Date');
    $element['time']['#attributes']['placeholder'] = t('Time');
  }
  return $element;
}

/**
 * Process file elements.
 */
function ux_form_managed_file_process(&$element, FormStateInterface $form_state, &$complete_form) {
  if (ux_form_access()) {
    $element['#theme_wrappers'][] = 'ux_form_element_container';
    $element['#wrapper_attributes']['class'][] = 'ux-form-file';
    $element['#attached']['library'][] = 'ux_form/ux_form.file';
  }
  return $element;
}

/**
 * Process text format elements.
 */
function ux_form_text_format_process(&$element, FormStateInterface $form_state, &$complete_form) {
  if (ux_form_access()) {
    $element['format']['#attributes']['class'][] = 'ux-form-text-format';
  }
  return $element;
}

/**
 * Prepares variables for container templates.
 *
 * Default template: container.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #id, #attributes, #children.
 */
function ux_form_preprocess_container(array &$variables) {
  $element = $variables['element'];
  if (isset($element['widget']['#field_name'])) {
    $variables['attributes']['class'][] = 'field-wrapper';
  }
}

/**
 * Prepares variables for container templates.
 *
 * Default template: ex-form-element-container.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - element: An associative array containing the properties of the element.
 *     Properties used: #id, #attributes, #children.
 */
function template_preprocess_ux_form_element_container(array &$variables) {
  $element = $variables['element'];
  $variables['attributes'] = [];
  $variables['children'] = $element['#children'];
  if (isset($element['#name'])) {
    $variables['attributes']['class'][] = 'ux-element-' . Html::getClass($element['#name']);
  }
}
