<?php

/**
 * @file
 * Contains ux_aside.module.
 */

/**
 * Implements hook_theme().
 */
function ux_aside_theme($existing, $type, $theme, $path) {
  return [
    'ux_asides' => [
      'variables' => [
        'content' => [],
        'attributes' => [],
      ],
      'file' => 'ux_aside.theme',
    ],
    'ux_aside' => [
      'variables' => [
        'content' => [],
        'attributes' => [],
        'content_attributes' => [],
      ],
      'file' => 'ux_aside.theme',
    ],
    'ux_aside_trigger' => [
      'variables' => [
        'label' => [],
        'attributes' => [],
      ],
      'file' => 'ux_aside.theme',
    ],
  ];
}

/**
 * Implements hook_preprocess_ux_wrapper().
 */
function ux_aside_preprocess_ux_wrapper(&$variables) {
  $variables['window_after']['asides'] = [
    '#type' => 'ux_asides',
  ];
}
