<?php

/**
 * @file
 * Contains ux.module.
 */

/**
 * Implements hook_element_info_alter().
 */
function ux_element_info_alter(&$type) {
  if (isset($type['page'])) {
    $type['page']['#theme_wrappers']['ux_wrapper'] = [
      '#attributes' => ['class' => ['ux-wrapper']],
      '#weight' => -1000,
    ];
    \Drupal::moduleHandler()->alter('ux_wrapper', $type['page']['#theme_wrappers']['ux_wrapper']);
  }
}

/**
 * Implements hook_theme().
 */
function ux_theme($existing, $type, $theme, $path) {
  $themes = array();
  $themes['ux_wrapper'] = [
    'variables' => [
      'children' => NULL,
      'attributes' => NULL,
      'pre_render' => [],
      'window_before' => [],
      'window_after' => [],
    ],
  ];
  // Form elements.
  $themes['ux_select_as_checkbox'] = [
    'render element' => 'element',
    'file' => 'ux.theme',
  ];
  $themes['ux_select_as_links'] = [
    'render element' => 'element',
    'file' => 'ux.theme',
  ];
  return $themes;
}

/**
 * Implements template_preprocess_form_element().
 */
function ux_preprocess_form_element(&$variables) {
  $element = &$variables['element'];
  if (isset($element['#theme']) && $element['#theme'] == 'ux_select_as_checkbox') {
    // Since the type is changed from select to checkbox, we want to make
    // sure the wrapper classes are set correctly.
    $variables['type'] = 'checkbox';
    $variables['attributes']['class'][] = 'from-select';
    $variables['label_display'] = 'hidden';
  }
}
