<?php

/**
 * @file
 * Contains ux_ui.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_preprocess_select().
 */
function ux_ui_preprocess_select(&$variables) {
  // $variables['#attached']['library'][] = 'ux_ui/ux_ui.dropdown';
  // $variables['attributes']['class'][] = 'ux-ui-select';
}

/**
 * Implements hook_preprocess_form_element().
 */
function ux_ui_preprocess_form_element(&$variables) {
  // $variables['attributes']['class'][] = 'input-field';
  // // $variables['attributes']['class'][] = 'inline';
  // if ($variables['label_display'] == 'before') {
  //   $variables['label_display'] = 'after';
  // }
}
