<?php

/**
 * @file
 * Contains ux_menu.module.
 */

/**
 * Implements hook_theme().
 */
function ux_menu_theme($existing, $type, $theme, $path) {
  return [
    'ux_menu' => [
      'variables' => [
        'menu' => [],
        'header' => [],
        'footer' => [],
        'options' => [],
        'attributes' => [],
      ],
      'file' => 'ux_menu.theme',
    ],
    'ux_menu_menu' => [
      'variables' => [
        'menu_name' => NULL,
        'levels' => [],
        'attributes' => [],
        'options' => [],
      ],
      'file' => 'ux_menu.theme',
    ],
  ];
}
