<?php

/**
 * @file
 * Contains ux_entity_browser.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 *
 * Overrides the core html theme to use a custom template for iframes.
 */
function ux_media_theme() {
  $path = drupal_get_path('module', 'entity_browser') . '/templates';
  return [
    'html__entity_browser__ux_aside' => [
      'template' => 'html--entity-browser--iframe',
      'render element' => 'html',
      'path' => $path,
      'preprocess functions' => ['template_preprocess_html'],
    ],
    'page__entity_browser__ux_aside' => [
      'template' => 'page--entity-browser--iframe',
      'render element' => 'html',
      'path' => $path,
      'preprocess functions' => ['template_preprocess_page'],
    ],
  ];
}

/**
 * Implements hook_preprocess_views_view().
 */
function ux_media_preprocess_media(&$variables) {
  // Always hide media names.
  $variables['content']['name']['#access'] = FALSE;
}

/**
 * Implements hook_preprocess_views_view().
 */
function ux_media_preprocess_views_view(&$variables) {
  if (substr($variables['view']->id(), 0, 9) === 'ux_media_') {
    $variables['view_array']['#attached']['library'][] = 'ux_media/view';
  }
}

/**
 * Implements hook_preprocess_html__entity_browser__modal().
 *
 * Tries to figure out where messages block lives and display it separately.
 */
function ux_media_preprocess_html__entity_browser__ux_aside(&$variables) {
  $variables['html_attributes']->addClass('ux-media-view');
}

/**
 * Implements hook_preprocess_page__entity_browser__modal().
 *
 * Tries to figure out where messages block lives and display it separately.
 */
function ux_media_preprocess_page__entity_browser__ux_aside(&$variables) {
  entity_browser_preprocess_page__entity_browser__iframe($variables);
}
