<?php

/**
 * @file
 * Contains ux_entity_browser.module.
 */

/**
 * Implements hook_theme().
 *
 * Overrides the core html theme to use a custom template for iframes.
 */
function ux_media_theme() {
  $path = drupal_get_path('module', 'entity_browser') . '/templates';
  return [
    'html__entity_browser__ux_aside' => [
      'template' => 'html--entity-browser--iframe',
      'render element' => 'html',
      'path' => $path,
      'preprocess functions' => ['template_preprocess_html'],
    ],
    'page__entity_browser__ux_aside' => [
      'template' => 'page--entity-browser--iframe',
      'render element' => 'html',
      'path' => $path,
      'preprocess functions' => ['template_preprocess_page'],
    ],
  ];
}

/**
 * Implements hook_preprocess_page__entity_browser__modal().
 *
 * Tries to figure out where messages block lives and display it separately.
 */
function ux_media_preprocess_page__entity_browser__ux_aside(&$variables) {
  entity_browser_preprocess_page__entity_browser__iframe($variables);
}
